name: Notify release to dependencies

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      TARGET_REPO: fmvilas/test-repo-2
    steps:
      - name: Set version environment variable
        run: |
          echo "RELEASE_VERSION=$(echo $GITHUB_REF | cut -c12-)" >> $GITHUB_ENV

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: 'fmvilas/test-repo-2'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: '${{github.repository}}/release'
          client-payload: '{"version":"${{env.RELEASE_VERSION}}"}'
          