name: Notify release to dependencies

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: notify
        run: |
          echo $GITHUB_REF | cut -c12-
          