name: Notify release to dependencies

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

  dispatch:
    needs: release
    strategy:
      matrix:
        repo: ['fmvilas/test-repo-2']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - id: package_details
        uses: ./.github/actions/package-details

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: '${{github.repository}}/release'
          client-payload: '{"name": "${{ steps.package_details.outputs.name }}", "version":"${{ steps.package_details.outputs.version }}"}'
          