name: Notify release to dependencies

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      TARGET_REPO: fmvilas/test-repo-2
    steps:
      - name: notify
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/$TARGET_REPO/dispatches" \
          -d '{"event_type": "$GITHUB_REPOSITORY/release", "client_payload": { "version": "${echo $GITHUB_REF | cut -c12-}" }}'
          